### ISSUE TITLE
Add FDIC to the list

### ISSUE THREAD

**Issue by jflamb** [ryanwoldatwork/digital-services#1]
I'm a recently hired UX/UI Designer at the FDIC (Federal Deposit Insurance Corporation). Our program is "FDIC Digital" and the website is https://www.fdic.gov/

**Comment by ryanwoldatwork** [comment]
Thanks @jflamb!

https://github.com/ryanwoldatwork/digital-services/commit/6875bb4df627ec1ec1c1730b0aaa53b6fc7d060d
